import { NextResponse } from "next/server"

export async function GET(request: Request) {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  const { searchParams } = new URL(request.url)
  const page = Number.parseInt(searchParams.get("page") || "1")
  const limit = Number.parseInt(searchParams.get("limit") || "8")

  const allUsers = [
    {
      id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
      role: "Admin" as const,
      status: "Active" as const,
      lastActive: "Today, 2:15 PM",
      avatar: "/professional-male-avatar.png",
    },
    {
      id: "2",
      name: "Sarah Miller",
      email: "sarah.miller@example.com",
      role: "Premium User" as const,
      status: "Active" as const,
      lastActive: "Today, 10:30 AM",
      avatar: "/professional-female-avatar.png",
    },
    {
      id: "3",
      name: "Alex Kim",
      email: "alex.kim@example.com",
      role: "User" as const,
      status: "Inactive" as const,
      lastActive: "Yesterday",
      avatar: "/professional-asian-avatar.png",
    },
    {
      id: "4",
      name: "Emma Roberts",
      email: "emma.roberts@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "3 days ago",
      avatar: "/professional-female-avatar-2.png",
    },
    {
      id: "5",
      name: "Michael Johnson",
      email: "michael.johnson@example.com",
      role: "Premium User" as const,
      status: "Active" as const,
      lastActive: "Today, 9:45 AM",
      avatar: "/professional-male-avatar-2.png",
    },
    {
      id: "6",
      name: "Lisa Wang",
      email: "lisa.wang@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "Yesterday",
      avatar: "/professional-asian-female-avatar.png",
    },
    {
      id: "7",
      name: "David Brown",
      email: "david.brown@example.com",
      role: "Premium User" as const,
      status: "Inactive" as const,
      lastActive: "Last week",
      avatar: "/professional-male-avatar-3.png",
    },
    {
      id: "8",
      name: "Sophia Martinez",
      email: "sophia.martinez@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "Today, 12:05 PM",
      avatar: "/professional-latina-avatar.png",
    },
    {
      id: "9",
      name: "Robert Wilson",
      email: "robert.wilson@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "2 hours ago",
      avatar: "/professional-male-avatar.png",
    },
    {
      id: "10",
      name: "Jennifer Davis",
      email: "jennifer.davis@example.com",
      role: "Premium User" as const,
      status: "Active" as const,
      lastActive: "Today, 1:30 PM",
      avatar: "/professional-female-avatar.png",
    },
    {
      id: "11",
      name: "Kevin Chen",
      email: "kevin.chen@example.com",
      role: "User" as const,
      status: "Inactive" as const,
      lastActive: "3 days ago",
      avatar: "/professional-asian-avatar.png",
    },
    {
      id: "12",
      name: "Amanda Taylor",
      email: "amanda.taylor@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "Yesterday",
      avatar: "/professional-female-avatar-2.png",
    },
    {
      id: "13",
      name: "Daniel Garcia",
      email: "daniel.garcia@example.com",
      role: "Admin" as const,
      status: "Active" as const,
      lastActive: "Today, 11:20 AM",
      avatar: "/professional-male-avatar-2.png",
    },
    {
      id: "14",
      name: "Rachel Lee",
      email: "rachel.lee@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "4 hours ago",
      avatar: "/professional-asian-female-avatar.png",
    },
    {
      id: "15",
      name: "Christopher Moore",
      email: "christopher.moore@example.com",
      role: "Premium User" as const,
      status: "Inactive" as const,
      lastActive: "Last week",
      avatar: "/professional-male-avatar-3.png",
    },
    {
      id: "16",
      name: "Maria Rodriguez",
      email: "maria.rodriguez@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "Today, 3:45 PM",
      avatar: "/professional-latina-avatar.png",
    },
    {
      id: "17",
      name: "James Anderson",
      email: "james.anderson@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "Yesterday",
      avatar: "/professional-male-avatar.png",
    },
    {
      id: "18",
      name: "Nicole Thompson",
      email: "nicole.thompson@example.com",
      role: "Premium User" as const,
      status: "Active" as const,
      lastActive: "Today, 8:15 AM",
      avatar: "/professional-female-avatar.png",
    },
    {
      id: "19",
      name: "Ryan Park",
      email: "ryan.park@example.com",
      role: "User" as const,
      status: "Inactive" as const,
      lastActive: "5 days ago",
      avatar: "/professional-asian-avatar.png",
    },
    {
      id: "20",
      name: "Jessica White",
      email: "jessica.white@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "2 days ago",
      avatar: "/professional-female-avatar-2.png",
    },
    {
      id: "21",
      name: "Matthew Clark",
      email: "matthew.clark@example.com",
      role: "Admin" as const,
      status: "Active" as const,
      lastActive: "Today, 4:30 PM",
      avatar: "/professional-male-avatar-2.png",
    },
    {
      id: "22",
      name: "Ashley Kim",
      email: "ashley.kim@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "6 hours ago",
      avatar: "/professional-asian-female-avatar.png",
    },
    {
      id: "23",
      name: "Brandon Lewis",
      email: "brandon.lewis@example.com",
      role: "Premium User" as const,
      status: "Inactive" as const,
      lastActive: "Last month",
      avatar: "/professional-male-avatar-3.png",
    },
    {
      id: "24",
      name: "Samantha Martinez",
      email: "samantha.martinez@example.com",
      role: "User" as const,
      status: "Active" as const,
      lastActive: "Today, 5:10 PM",
      avatar: "/professional-latina-avatar.png",
    },
  ]

  const total = allUsers.length
  const totalPages = Math.ceil(total / limit)
  const startIndex = (page - 1) * limit
  const endIndex = startIndex + limit
  const users = allUsers.slice(startIndex, endIndex)

  return NextResponse.json({
    users,
    total,
    currentPage: page,
    totalPages,
  })
}
